import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps.home',
        path: `${APP_PREFIX_PATH}/inicio`,
        title: 'Início',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [USER],
        subMenu: [],
    },
    {
        key: 'apps.entities',
        path: '',
        title: 'Entidades',
        icon: 'entities',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsProject.dashboard',
                path: '',
                title: 'Adicionar Entidade',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsProject.teste',
                        path: '',
                        title: 'Listar Entidades 2',
                        icon: '',
                        type: NAV_ITEM_TYPE_COLLAPSE,
                        authority: [USER],
                        subMenu: [
                            {
                                key: 'appsProject.teste2',
                                path: 'https://teste.cacbempreenderapp.org.br/sistema/associacao/',
                                title: 'Listar Entidades 3',
                                icon: '',
                                translateKey: 'Listar Entidades 3',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [USER],
                                subMenu: [],
                            },
                        ],
                    },
                ],
            },
            {
                key: 'appsProject.projectList',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/associacao/',
                title: 'Listar Entidades',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsProject.scrumBoard',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/diagnosticos/lista-diagnosticos-geral',
                title: 'Diagnósticos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsProject.issue',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/diagnosticos/painel-diagnosticos',
                title: 'Painel de Diagnósticos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsProject.issue',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/associacao/painel',
                title: 'Perfil das ACEs',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.nucleos',
        path: '',
        title: 'Núcleos',
        icon: 'nucleos',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsCrm.dashboard',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/nucleo/adicionar/',
                title: 'Adicionar Núcleo',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsCrm.calendar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/plano-acao/adicionar/',
                title: 'Adicionar Plano de Ação',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsCrm.customers',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/reuniao/adicionar/',
                title: 'Adicionar Reunião',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsCrm.customerDetails',
                path: `${APP_PREFIX_PATH}/nucleos`,
                title: 'Listar Núcleos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsCrm.teste',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/plano-acao/',
                title: 'Listar Planos de Ação',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsCrm.teste2',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/reuniao/',
                title: 'Listar Reuniões',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.empresas',
        path: '',
        title: 'Empresas',
        icon: 'companies',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsEmpresas.adicionar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/adicionar/',
                title: 'Adicionar Empresa',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsEmpresas.listar',
                path: `${APP_PREFIX_PATH}/empresas`,
                title: 'Listar Empresas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsEmpresas.minhas',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/minhas-empresas',
                title: 'Minhas Empresas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.usuarios',
        path: '',
        title: 'Usuários',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsUsuarios.adicionar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/usuario/adicionar/',
                title: 'Adicionar Usuário',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsUsuarios.listar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/usuario/',
                title: 'Listar Usuários',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.relatorios',
        path: '',
        title: 'Relatórios',
        icon: 'reports',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsRelatorios.adicionar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/gerador-relatorio/modelo',
                title: 'Adicionar Relatório',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsRelatorios.listar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorio/',
                title: 'Listar Relatórios',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.projetos',
        path: '',
        title: 'Projetos',
        icon: 'project',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsProjetos.acompFinanceiro',
                path: '',
                title: 'Acompanhamento financeiro',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsProjetos.painelEntidades',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/painel-entidades/',
                        title: 'Painel das Entidades Proponentes',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['painel_entidades_origens'],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.painelGestao',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/painel-gestao-financeira/',
                        title: 'Painel Gestão Financeira',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['painel_gest_fin'],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.projetosApoiadosFin',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/projetos-apoiados-financeiro/',
                        title: 'Projetos Apoiados - FIN',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.situacaoProjetos',
                        path: '',
                        title: 'Situação dos projetos',
                        icon: '',
                        type: NAV_ITEM_TYPE_COLLAPSE,
                        authority: [USER],
                        subMenu: [
                            {
                                key: 'appsProjetos.projSemLanc',
                                path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/painel-situacao-projetos/?tipo=periodo',
                                title: 'Projetos sem lançamentos no período',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [USER],
                                subMenu: [],
                            },
                            {
                                key: 'appsProjetos.projLancAnalise',
                                path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/painel-situacao-projetos/?tipo=analise',
                                title: 'Projetos com lançamentos para análise',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [USER],
                                subMenu: [],
                            },
                        ],
                    },
                    {
                        key: 'appsProjetos.transferenciasPagamentos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/transferencias-e-pagamentos-novo',
                        title: 'Transferências e Pagamentos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsProjetos.acompTecnico',
                path: '',
                title: 'Acompanhamento técnico',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsProjetos.acompPesquisa',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/painel-acompanhamento',
                        title: 'Acompanhamento da pesquisa',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.docsAguardandoAprovacao',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/painel-aguardando',
                        title: 'Documentos aguardando aprovação',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.projetosApoiadosTec',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/projetos-apoiados-tec',
                        title: 'Projetos Apoiados - TEC',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsProjetos.auditoria189',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/projeto-auditoria/',
                title: 'Auditoria 189',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsProjetos.acompSebrae',
                path: '',
                title: 'E2022 - Acompanhamento Sebrae',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsProjetos.despesasAcomp',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/despesas-acompanhamento',
                        title: 'Acompanhamento de despesas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsProjetos.e2022AlInvest',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/concursos-geral/',
                title: 'E2022 / AL Invest Verde',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsProjetos.premio21',
                path: '',
                title: 'Prêmio 21',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['USER'],
                subMenu: [
                    {
                        key: 'appsProjetos.avaliacaoFinal',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/avaliacao-final',
                        title: 'Avaliação final',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.listaPropostas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/lista-propostas/',
                        title: 'Lista de Propostas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.painelPremio21',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/painel',
                        title: 'Painel',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.relatorioNotas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/relatorio-notas',
                        title: 'Relatório de Notas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProjetos.resultadoFinal',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/avaliacao-final',
                        title: 'Resultado final',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
    {
        key: 'apps.arquivos',
        path: '',
        title: 'Arquivos',
        icon: 'files',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['USER'],
        subMenu: [
            {
                key: 'appsArquivos.listar',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/arquivos',
                title: 'Listar Arquivos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.curriculos',
        path: '',
        title: 'Currículos',
        icon: 'curriculos',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsCurriculos.listarCurriculos',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/curriculo/',
                title: 'Listar Currículos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsCurriculos.listarUsuarios',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/usuariocv/',
                title: 'Listar Usuários',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'apps.adm',
        path: '',
        title: 'ADM',
        icon: 'adm',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [USER],
        subMenu: [
            {
                key: 'appsAdm.acompanhamentoGeral',
                path:
                    'https://teste.cacbempreenderapp.org.br/sistema/adminutils/acompanhamento-geral/quadro/' +
                    btoa('quadro1'),
                title: 'Acompanhamento geral',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsAdm.ajustesDados',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/prestcontas/atualizacao-lancamento',
                title: 'Ajustes de Dados',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsAdm.concurso',
                path: '',
                title: 'Concurso',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsAdm.avaliadores',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/avaliador-lista',
                        title: 'Avaliadores',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.categorias',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/categoria-lista',
                        title: 'Categorias',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.concursos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/index',
                        title: 'Concursos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.quesitos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/concurso/quesito-lista',
                        title: 'Quesitos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.diagnosticos',
                path: '',
                title: 'Diagnósticos',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'appsAdm.quesitosDiagnostico',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/diagnosticos/quesitos-diagnostico-lista',
                        title: 'Quesitos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.consultores',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/diagnosticos/consultor-lista',
                        title: 'Consultores',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.entidadesCadastradas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/diagnosticos/entidades-lista',
                        title: 'Entidades cadastradas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.direitos',
                path: '',
                title: 'Direitos',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['adm_direitos'],
                subMenu: [
                    {
                        key: 'appsAdm.associacaoGestorRecurso',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/gestor-recurso/',
                        title: 'Associação Gestor-Recurso',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.associacaoPerfilRecurso',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/aclrecurso/',
                        title: 'Associação Perfil-Recurso',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaDireitos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/direitos/index',
                        title: 'Lista de direitos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.perfis',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/usuarios/perfil-lista',
                        title: 'Perfis',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.recurso',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/recurso/',
                        title: 'Recurso',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.documentos',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/documento/',
                title: 'Documentos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsAdm.empresas',
                path: '',
                title: 'Empresas',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'appsAdm.cadastroEmpresa',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/cadastro',
                        title: 'Cadastro empresa',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.cadastroRamoAtividade',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/ramoatividade',
                        title: 'Cadastro ramo atividade',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaEmpresas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/index',
                        title: 'Lista empresas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaEmpreendimentos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/empreendimentos',
                        title: 'Lista empreendimentos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaRamosAtividades',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/ramoatividade-lista',
                        title: 'Lista ramos atividades',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaTipoEmpreendimento',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/empresa/tipoempreendimento-lista',
                        title: 'Lista tipo empreendimento',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.estatisticas',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/estatisticas/',
                title: 'Estatísticas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsAdm.eventos',
                path: '',
                title: 'Eventos',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsAdm.cadastroEvento',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/eventos/cadastro',
                        title: 'Cadastro',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.participantes',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/eventos/participantes',
                        title: 'Participantes',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.programacao',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/eventos/programacao',
                        title: 'Programação',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.tiposEventos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/eventos/tipos',
                        title: 'Tipos eventos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.informacoes',
                path: '',
                title: 'Informações',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsAdm.boletins',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/boletim/',
                        title: 'Boletins',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.etapasCiclos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/etapas-ciclos/',
                        title: 'Etapas Ciclos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.menu',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/menu/',
                        title: 'Menu',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.textos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/texto/',
                        title: 'Textos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.integrantes',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/integrantes/',
                title: 'Integrantes',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsAdm.noticias',
                path: '',
                title: 'Notícias',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'appsAdm.cadastroNoticia',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/noticias/cadastro',
                        title: 'Cadastro',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaNoticias',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/noticias/index',
                        title: 'Lista',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.recursos',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/recurso/',
                title: 'Recursos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsAdm.regras',
                path: 'https://teste.cacbempreenderapp.org.br/sistema/adminutils/regras/',
                title: 'Regras',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsAdm.relatorios',
                path: '',
                title: 'Relatórios',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'appsAdm.diagnosticos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorios/diagnosticos',
                        title: 'Diagnósticos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.empresas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorios/empresas',
                        title: 'Empresas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.eventos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorios/eventos',
                        title: 'Eventos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listagens',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorios/listagens',
                        title: 'Listagens',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.pontuacaoGeral',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorios/pontuacao-geral',
                        title: 'Pontuação Geral',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.recursos',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/relatorios/recursos',
                        title: 'Recursos',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.usuarios',
                path: '',
                title: 'Usuarios',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'appsAdm.associados',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/usuarios/associado-lista',
                        title: 'Associados',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.auditores',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/usuarios/auditor-lista',
                        title: 'Auditores',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.empresasUsuarios',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/usuarios/empresa-lista',
                        title: 'Empresas',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.gestores',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/usuarios/gestor-lista',
                        title: 'Gestores',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.usuarios',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/usuarios/usuario-lista',
                        title: 'Usuários',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsAdm.videoaulas',
                path: '',
                title: 'Videoaulas',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [USER],
                subMenu: [
                    {
                        key: 'appsAdm.categoriasVideoaulas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/videoaulas/categorias',
                        title: 'Categorias',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.listaVideoaulas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/videoaulas/lista',
                        title: 'Lista',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'appsAdm.tagsVideoaulas',
                        path: 'https://teste.cacbempreenderapp.org.br/sistema/videoaulas/tags',
                        title: 'Tags',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default appsNavigationConfig
