name: Deploy to Homolog Server

on:
  push:
    branches: [ homolog ]

jobs:
  build:

#aaas
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Installing node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Creating .env file
      run: echo "VITE_API_URL=https://beta.homolog.cacbempreenderapp.org.br/" > .env && echo "VITE_PHP_URL=https://homolog.cacbempreenderapp.org.br" >> .env
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Homolog Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "167.71.96.115"
          REMOTE_USER: "root"
          TARGET: "/usr/share/nginx/html/Empreender.Frontend"
          EXCLUDE: "/dist/, /node_modules/"
