name: CI

on:
  push:
    branches:
      - Elstar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh -t root@167.99.157.110 "mkdir foi"  
